name: Build CircleFTP Aniyomi Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the APK
        run: ./gradlew assembleRelease

      - name: Show APK path (manual download workaround)
        run: ls -R app/build/outputs/apk/release/